/**
 * Take in answers to multiple choice questions and generate a string from a
 * lookup table.
 * 
 * This implementation assumes 3 questions each with 4 choices. 
 */

#include "quiz_score.h"

#include "utils.h"

uint32_t score;
uint8_t score_idx;
void ClearScore() {
  score = 0;
  score_idx = 0;
}

void AddToScore(uint8_t choice) {
  score += choice << (2 * score_idx);
  score_idx++;
}

// Tables generated by python\specify_story.py
const char DOLL_TYPES_0[] PROGMEM = "Voodoo";
const char DOLL_TYPES_1[] PROGMEM = "Chucky-esque";
const char DOLL_TYPES_2[] PROGMEM = "Melted Wax";
const char DOLL_TYPES_3[] PROGMEM = "Sewn Skin";
const char DOLL_TYPES_4[] PROGMEM = "Non-Euclidean";
const char DOLL_TYPES_5[] PROGMEM = "Porcelain";
const char DOLL_TYPES_6[] PROGMEM = "Eldritch";
const char DOLL_TYPES_7[] PROGMEM = "Clown";
const char *const DOLL_TYPES[] PROGMEM = {DOLL_TYPES_0, DOLL_TYPES_1, DOLL_TYPES_2, DOLL_TYPES_3, DOLL_TYPES_4, DOLL_TYPES_5, DOLL_TYPES_6, DOLL_TYPES_7};

const char DOLL_ADJECTIVES_0[] PROGMEM = "Glowing";
const char DOLL_ADJECTIVES_1[] PROGMEM = "Whispering";
const char DOLL_ADJECTIVES_2[] PROGMEM = "Floating";
const char DOLL_ADJECTIVES_3[] PROGMEM = "Giggling";
const char DOLL_ADJECTIVES_4[] PROGMEM = "Bent";
const char DOLL_ADJECTIVES_5[] PROGMEM = "Cracked";
const char DOLL_ADJECTIVES_6[] PROGMEM = "Eyeless";
const char DOLL_ADJECTIVES_7[] PROGMEM = "Vibrating";
const char *const DOLL_ADJECTIVES[] PROGMEM = {DOLL_ADJECTIVES_0, DOLL_ADJECTIVES_1, DOLL_ADJECTIVES_2, DOLL_ADJECTIVES_3, DOLL_ADJECTIVES_4, DOLL_ADJECTIVES_5, DOLL_ADJECTIVES_6, DOLL_ADJECTIVES_7};

void CopyScoreStr(char * buffer) {
  uint8_t idx1 = score & 0b111;
  uint8_t idx2 = (score >> 3) & 0b111;
  const char* adj_ptr = (const char*)pgm_read_ptr(DOLL_ADJECTIVES + idx1);
  buffer = PrgmStrCpy(buffer, adj_ptr);
  buffer = PrgmStrCpy(buffer, PSTR(" "));
  const char* type_ptr = (const char*)pgm_read_ptr(DOLL_TYPES + idx2);
  buffer = PrgmStrCpy(buffer, type_ptr);
  buffer = PrgmStrCpy(buffer, PSTR(" Dolls"));
}
